spring.application.name=github-client1
logging.level.root=INFO
logging.level.com.example.githubclient1=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/githubdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:github}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:github123}