spring.application.name=github-client1
logging.level.com.example.githubclient1.client.GithubClient=DEBUG
spring.datasource.url=jdbc:h2:mem:githubdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
